### ISSUE TITLE
Project Shims of NPM packages with names that are less then 3 characters is not possible

### ISSUE THREAD

**Issue by danielang** [SAP/ui5-tooling#1039]
## Expected Behavior
Be able to include a npm package where the name is less than 3 characters.

## Current Behavior
![Image](https://github.com/user-attachments/assets/731d944f-0d29-47fc-b526-f39cb800e4f6)
The behavior follows the schema: https://sap.github.io/ui5-tooling/stable/pages/Configuration/#name 

## Steps to Reproduce the Issue

1. Install dependency e.g. `npm i --save ol`
2. Include project shim config in ui.yaml:
```yaml
---
specVersion: "4.0"
kind: extension
type: project-shim
metadata:
  name: my.application.thirdparty
shims:
  configurations:
    ol: # name as defined in package.json
      specVersion: "4.0"
      type: module # Use module type
      metadata:
        name: ol
      resources:
        configuration:
          paths:
            /resources/my/application/thirdparty/: ""

```
3. Start ui5 cli `ui5 serve`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`4.0.6`**
 * Node.js Version: **`v22.11.0`**
 * npm Version: `10.9.0`
 * OS/Platform: `Windows 11 - 64Bit`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by d3xter666** [comment]
Hi @danielang,

Please, check carefully the schema validation. The name `ol` does not follow the standard.

Cheers

**Comment by danielang** [comment]
I already pointed that out that the schema does not align.
The problem is that I want to include the npm package via a project shim. It is obviously required to use the name of the package as the key of the shim configuration. See line `ol: # name as defined in package.json`.

I can not change the name of that package. It is just named `ol`. It only has 2 characters as name. How can I shim it?

**Comment by danielang** [comment]
Hey @flovogt,
that works for me.

Just one small thing I noticed:
ui5-serve automatically included the shim, while for the builder I manually had to mention the dependency in the settings:
```yaml
builder:
  settings:
    includeDependency:
      - ol-ui5
```
