### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by luizbag** [SAP/ui5-tooling#1046]
## Expected Behavior
I should be able to build my ui5 application.

## Current Behavior
Instead, I get the error below:
No "exports" main defined in C:\repos\app\node_modules\@ui5\builder\package.json

## Steps to Reproduce the Issue

1. I have a ui5 app;
2. Use the build command: ```ui5 build --verbose --config=ui5.yaml --clean-dest --all --dest=./build/dist --exclude-task=createDebugFiles --include-task=generateLibraryPreload generateVersionInfo```
3. Get the error

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`4.0.13`**
 * Node.js Version: **`20.17.0`**
 * npm Version: `11.0.0`
 * OS/Platform: `Windows 11`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
⚠️  Process Failed With Error

Error Message:
No "exports" main defined in C:\repos\app\node_modules\@ui5\builder\package.json


Stack Trace:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\repos\app\node_modules\@ui5\builder\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\repos\app\tasks\generateCacheBusterFiles.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
```

**Comment by d3xter666** [comment]
Hi @luizbag ,

Would you share the `ui5.yaml` you're using. I tried to reproduce the issue with https://github.com/SAP/openui5-sample-app, but it's not reproducible there. I suspect it could be some of the build tasks in `ui5.yaml`

Cheers

**Comment by luizbag** [comment]
Sure, here it is:

```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.2"
metadata:
  name: com.leroli.globalapps
type: application
framework:
  name: OpenUI5
  version: "1.96.6"
  libraries:
    - name: sap.m
    - name: sap.ui.core
    - name: sap.uxap
    - name: sap.ui.table
    - name: sap.f
    - name: sap.tnt
    - name: sap.ui.support
    - name: themelib_sap_fiori_3
builder:
  customTasks:
    - name: generate-cachebuster-files
      afterTask: generateVersionInfo
---
specVersion: "3.2"
kind: extension
type: task
metadata:
  name: generate-cachebuster-files
task:
  path: tasks/generateCacheBusterFiles.js
```
