### ISSUE TITLE
Self-contained app with specific UI5 version is being loaded with launchpad UI5 version

### ISSUE THREAD

**Issue by federicobelotti** [SAP/ui5-tooling#1052]
Hello,
I'm having troubles with a self-contained UI5 app built to be used with UI5 version 1.130.0 (as stated in the `ui5.yaml` file). This app is being opened from a Launchpad that is using the latest version (1.134.0) and both Launchpad and the application have been deployed on an on-premise webserver.
The problem is that when I open the application directly (without going through the Launchpad) it is correctly using the version specified during the build (I can in fact see that inside the `sap-ui-version.json` file there's a reference to version 1.130.0), but when opening it from the Launchpad it is loading version 1.134.0 and it doesn't work correctly.
Our goal is to freeze the version despite what's being loaded from the Launchpad.

This is the build configuration in the `ui5.yaml` file:
```yaml
framework:
  name: SAPUI5
  version: "1.130.0"
  libraries:
    - name: sap.fe.core
    - name: sap.fe.templates
    - name: sap.insights
    - name: sap.m
    - name: sap.ui.core
    - name: sap.ui.dt
    - name: sap.ui.export
    - name: sap.ui.layout
    - name: sap.ui.rta
    - name: sap.ui.support
    - name: sap.ui.testrecorder
    - name: sap.ui.vk
    - name: sap.ushell
```
The application has been built with this command:
`ui5 build self-contained --dest contained --clean-dest --include-all-dependencies --include-task generateVersionInfo`

Why a self-contained application does not use self-contained libraries as I would have expected it to?

Thanks
