### ISSUE TITLE
[QUESTION] Use Library with a different yaml file

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-tooling#1070]
Hi UI5 Team,

**Goal**
In my application I sometimes want to consume the sources of an internal library (for live debugging), and at other times the compiled **`dist`** bundle – *without* touching the library’s own `ui5.yaml`.

**Setup**

```text
my-app/                     (UI5 application)
  ui5.yaml
  package.json  ← npm link @my/org/ui5-utilslib

ui5-utilslib/               (linked library)
  ui5.yaml    # current default – points to dist
  src/
  dist/
```

`ui5-utilslib/ui5.yaml` today:

```yaml
type: library
resources:
  configuration:
    paths:
      src: dist/resources/customnamespace/
      test: dist/customnamespace/
```

If I manually change those two paths to `src/` and `test/`, the app uses the original sources, which is exactly what I need while developing – but that means hacking the library on disk.

**Question**
Is there a way in **UI5 Tooling** (e.g., via command-line flag, environment variable, or an override in the *application’s* `ui5.yaml`) to tell the CLI:

*“For the dependency `@my/org/ui5-utilslib`, load from `src/` instead of `dist/`”?*

Or is there a recommended alternative to switch between the two variants without modifying the library itself?

Thanks for any hints!
