### ISSUE TITLE
[Clarification] Environment variables in configuration(yaml) file

### ISSUE THREAD

**Issue by yramamurthy** [SAP/ui5-tooling#211]
How do I make use of an environment variable in the yaml configuration file? 

```
specVersion: '1.0'
metadata:
  name: ui5proj1
type: application
builder:
  customTasks:
  - name: ui5-task-nwabap-deployer
    afterTask: generateVersionInfo
    configuration: 
      resources:
        pattern: "**/*.*"
      connection:
        server: server.com
        client: 100
        useStrictSSL: false 
      authentication:
        user:<ENVIRONMENT VARIABLE>
        password: <ENVIRONMENT VARIBALE>
      ui5:
        language: EN
        package: $YR
        bspContainer: ZFIRSTAPP1
```

I am trying to avoid hardcoding of user/password in my example config file above.
