### ISSUE TITLE
path mapping doesn't work

### ISSUE THREAD

**Issue by stesap** [SAP/ui5-tooling#250]
## Expected Behavior
Path mapping declaration for external modules (e.g. a module id: **sap.se.mi.plm.lib.attachmentservice**) can be done like it is expected/[documented](https://sap.github.io/ui5-tooling/pages/Configuration/#path-mapping-of-modules).

The structure of the project is the following:

```sh
├── karma.ci.conf.js
├── karma.conf.js
├── node_modules/
├── package-lock.json
├── package.json
├── se
    └── mi
        └── plm
            └── lib
                └── attachmentservice
                    ├── attachment/
                    ├── library.js
                    ├── manifest.json
                    └── neo-app.json
├── ui5-ci.yaml
├── ui5-local.yaml
├── ui5.yaml
├── webapp/
``` 

## Current Behavior
Configuration with (all?) path mappings are invalid

## Steps to reproduce the issue
1. enter path mappings in `ui5.yaml`
```yaml
specVersion: '2.1'
metadata:
  name: 'ui-app-with-attachments'
type: application
framework:
  name: SAPUI5
  version: "1.78.2"

resources:
  configuration:
    paths:
      #see file structure above 'se' folder is on root level
      /resources/sap/se/mi/plm/lib/attachmentservice: se/mi/plm/lib/attachmentservice
```

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `2.3.1 (from ui-app-with-attachments/node_modules/@ui5/cli/bin/ui5.js)`
- Node.js Version: `v12.16.0`
- npm Version: `6.13.4`
- OS/Platform: `macOS`

## Affected components *(if known)*
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [x] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
> ui5 serve


⚠️  Process Failed With Error

Error Message:
Invalid ui5.yaml configuration for project manage-routes-ui

Configuration resources/configuration/paths property /resources/sap/se/mi/plm/lib/attachmentservice must not be provided here

/Users/d060015/code/ilo/Manage-Routes-UI/ui5.yaml:12

10:   configuration:
11:     paths:
12:       /resources/sap/se/mi/plm/lib/attachmentservice: se
          ^
```

## Current workaround
I got it working with the custom middleware [ui5-middleware-servestatic](https://github.com/petermuessig/ui5-ecosystem-showcase/tree/master/packages/ui5-middleware-servestatic) by petermuessig and vobu, but it feels more natural to use path mappings of UI5 Tooling. Also with this workaround, karma tests are not working.
