### ISSUE TITLE
SAPUI5 1.71 is not supported

### ISSUE THREAD

**Issue by DenisTis** [SAP/ui5-tooling#265]
Dear team, this setup is not supported by the tool: 

```
specVersion: "2.2"
type: application
metadata:
  name: CompanyRepo.appName
framework:
  name: SAPUI5
  version: 1.71.26
```
Could you please enable it for all SAPUI5 versions, which are on maintenance mode:
(https://sapui5.hana.ondemand.com/versionoverview.html )

**Comment by DenisTis** [comment]
I tried it also with version 1.71.0 - same result

**Comment by RandomByte** [comment]
Hi @DenisTis,

The minimum SAPUI5 version that can be installed by the UI5 Tooling is 1.76.0. 

The command `ui5 use sapui5@1.71.26` will also output the following error message:
> Could not resolve framework version 1.71.26. Note that SAPUI5 framework libraries can only be consumed by the UI5 Tooling starting with SAPUI5 v1.76.0

However, there are workarounds for simple local development use cases. We plan on writing a blog post or similar illustrating those.

In your projects `index.html` you could for example use the CDN URL `https://sapui5.hana.ondemand.com/resources/sap-ui-core.js` for bootstrapping UI5. You can also use the “simpleproxy” middleware from https://petermuessig.github.io/ui5-ecosystem-showcase/ to proxy a CDN hosted 1.71 version for local use. To work fully offline, you can also download a runtime archive from https://tools.hana.ondemand.com/#sapui5 and serve it using the “servestatic” middleware, also from the ui5-ecosystem-showcase project.

You can find a related discussion in the OpenUI5 Slack: https://openui5.slack.com/archives/C0A7MHSSJ/p1597649506340800 ([invite](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/))

**Comment by treee111** [comment]
Hi @RandomByte,
should this work for proxying a e.g. UI5 1.71.35 version for usage with ui5tooling?
For me this does not work...
```
server:
  customMiddleware:
  - name: ui5-middleware-simpleproxy
    afterMiddleware: compression
    mountPath: /resources
    configuration:
      baseUri: "https://sapui5.hana.ondemand.com/1.71.35/resources/sap-ui-core.js"
      strictSSL: false
```

Thanks!
