### ISSUE TITLE
Usage of self-contained bundle: errors and warnings during build and in browser console

### ISSUE THREAD

**Issue by mikrivorot** [SAP/ui5-tooling#301]
## Expected Behavior
It seems to be possible to reduce size of build folder during `ui5 build` script execution using `self-contained` and `--exclude-task=createDebugFiles`

as described in issues:
 [How to build the "most optimized" package by ui5 command](https://github.com/SAP/ui5-tooling/issues/224)
[Provide and document options to reduce content of build result](https://github.com/SAP/ui5-builder/issues/113)

## Current Behavior
Build folder with reduced (twice) size, but with errors and warnings during build and in browser console due to parameter `self-contained` (no errors with `--exclude-task=createDebugFiles` without `self-contained`)
_But application works well after build!_

## Steps to reproduce the issue
1. Use @ui/cli library
2. Have fragments.xml files and custom controls in project
3. Run `ui5 build self-contained --all --exclude-task=createDebugFiles`

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `2.2.2`
- Node.js Version: `12.13.1`
- npm Version: `6.12.1`
- OS/Platform: `Windows`
- Browser *(if relevant)*: `Chrome, Firefox`
- Other information:
-- `ui5.yaml` file content
```
specVersion: '2.1'
metadata:
  name: staticui5
type: application
framework:
  name: SAPUI5
  version: 1.77.2
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.ui.comp
    - name: sap.ui.codeeditor
    - name: sap.ui.layout
    - name: sap.tnt
    - name: sap.ui.table
    - name: themelib_sap_belize
    - name: sap.ui.unified
    - name: sap.uxap
```

## Affected components

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
- Errors during command `ui5 build self-contained --all --exclude-task=createDebugFiles` run

```
...
ERR! lbt:bundle:Resolver **** error: missing module sap/ui/support/Bootstrap.js, required by sap/ui/core/Core.js
ERR! lbt:bundle:Resolver **** error: missing module sap/ui/testrecorder/Bootstrap.js, required by sap/ui/core/Core.js
...
ERR! lbt:bundle:Resolver **** error: missing module <project home name>/utilities/<file with reusable logic inside>.js, required by <project home name>/Component/pages/<name>.controller.js
...
ERR! lbt:bundle:Resolver **** error: missing module <project home name>/controls/<custom control name>.js, required by <project home name>/Component/utilities/<file with reusable logic inside>.js
...
ERR! lbt:bundle:Resolver **** error: missing module <path to controller>/<name>.controller.js, required by <path to view>/<name>.view.xml
...
```

- Warnings during command `ui5 build self-contained --all --exclude-task=createDebugFiles` run
```
...
WARN lbt:bundle:Builder **** warning: module <project home name>/Component/utilities/<file with reusable code>.js requires top level scope and can only be embedded as a string (requires 'eval')
...
```

- Errors in browser console
```
failed to load 'sap/ui/core/library-preload' (failed to load 'sap/ui/core/library-preload.js' from static/sapui5/dist/resources/sap/ui/core/library-preload.js: 404 - Not Found) 
failed to load 'static/sapui5/dist/resources/sap/m/library-preload.json': Not Found
...
```
Looks like errors are similar to errors in issue [Explain how self-contained build can be split in multiple parts](https://github.com/SAP/ui5-builder/issues/163)
