### ISSUE TITLE
Performace lose when moving custom task to an seperate npm project

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-tooling#308]
We moved our custom tasks for the ui5 tooling to an seperat npm module. This containes following 
ui5.yaml 

```yaml
---
specVersion: '1.0'
kind: extension
type: task
metadata:
  name: someTaks
task:
  path: tasks/someTask.js

---
specVersion: '1.0'
kind: extension
type: task
metadata:
  name: someOtherTask
task:
  path: tasks/someOtherTask.js
---
specVersion: '1.0'
kind: extension
type: task
metadata:
  name: andAnotherTaks
task:
  path: tasks/andAnotherTaks.js
```

for all this tasks we need some dependencies
```json
{
    "@ui5/fs": "1.0.0",
    "@ui5/project": "1.0.0",
    "@ui5/server": "1.0.0",
    "cors": "2.8.5",
    "express": "4.16.4",
    "fs-extra": "7.0.1",
    "http-proxy": "1.17.0",
    "less-openui5": "0.6.0",
    "xml2js": "0.4.19"
}
```

Now everything is going well, we can declare this node module as dependecie in the app and use the tasks defined there. But as we need to define this all as npm dependencie and not as devDependencie the  npm translators translator analizes the dependencies of the module containg the tasks too even if they are no way needed in the ui5 project.

Would it be possible to implement an flag that says analyze this repo but ignore my dependencies?
