### ISSUE TITLE
Request help on the configuration with multiple modules in one repo 

### ISSUE THREAD

**Issue by 77Esther** [SAP/ui5-tooling#328]
Hi colleagues,

I am from the SAP product team. I want to ask for help on the ui5-server configuration for our case. 
I would be appreciated if you could help

Our application structure is like this:
```
cdt/
    \_ src/sap/dm/fnd/cdt/
        \_ library.js
        \_ ...
    \_ ui5.yaml
    \_ package.json
serviceregistry2/
    \_ webapp/
        \_ ...
    \_ ui5.yaml
    \_ package.json
package.json
```
And serviceregistry2 depends on the library cdt.

## Expected Behavior
I want to run the serviceregistry2 locally with the following command:
`"start": "ui5 serve --config=serviceregistry2/ui5.yaml  --open index.html"`
However, I don't know how to configure the resource.

## Current Behavior
I tried two options:
1. Define the cdt resources with relative path in the index.html. However, the resource cannot be reached.

2. Use extension and configured like this:
```
specVersion: "2.2"
metadata:
  name: serviceregistry
type: application
resources:
  configuration:
    paths:
      webapp: serviceregistry2/webapp
framework:
  name: SAPUI5
  version: 1.76.0
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.ui.layout
    - name: sap.uxap
    - name: themelib_sap_fiori_3
    - name: sap.ui.comp
    - name: sap.ui.codeeditor

server:
  settings:
    httpPort: 9090
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: serviceregistry2/webapp

--- # Everything below this line could also be put into the ui5.yaml of a standalone extension module
specVersion: "2.2"
kind: extension
type: project-shim
metadata:
  name: sap.dm.fnd.cdt
shims:
  configurations:
    sap.dm.fnd.cdt: # name as defined in package.json
      specVersion: "2.2"
      type: module # Use module type
      metadata:
        name: sap.dm.fnd.cdt
      resources:
        configuration:
          paths:
            /resources/sap/dm/fnd/cdt/: cdt/src/sap/dm/fnd/cdt # map root directory of lodash module
```

## Steps to reproduce the issue
You could find our source code on SAP GitHub Enterprise at DigitalManufacturing/fnd-serviceregistry-ui/tree/DIGMANEXE-41923.
Just run the following command and you will be able to reproduce the issue
```
npm install
npm start
```

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `2.4.4`
- Node.js Version: `v13.5.0`
- npm Version: `6.13.4`
- OS/Platform: `MacOS Catalina`
- Browser *(if relevant)*: `Chrome`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

Please help.
Thank you.
