### ISSUE TITLE
middlewareRepository: Unknown custom middleware

### ISSUE THREAD

**Issue by danielang** [SAP/ui5-tooling#332]
## Expected Behavior
The middleware should be loaded correctly.

## Current Behavior
All custom middlewares specified in ui5.yaml were not found by the ui5-server.
In the `projectPreprocessor` the middlewares were added to the [middlewareRepository of the ui5-server](https://github.com/SAP/ui5-project/blob/master/lib/projectPreprocessor.js#L514) . But if they should be added by the [MiddlewareManager](https://github.com/SAP/ui5-server/blob/master/lib/middleware/MiddlewareManager.js#L37) the middlewareRepository only contains the default middlewares and the custom one could not be found.

## Steps to reproduce the issue
1. Create a custom middleware
```javascript
module.exports = function({resources, options}) {
	options.configuration = options.configuration || {};

	return function (req, res, next) {
		res.end('Hello World!');
	}
};
```
saved in the location: `cli/middlewares/webpack-dev-middleware.js`
2. Add it to the ui5.yaml
```yaml
specVersion: '1.0'
metadata:
  name: "lbvis-sap-ui"
type: application
resources:
  configuration:
    paths:
      webapp: "/webapp"
    propertiesFileSourceEncoding: "UTF-8"
server:
  customMiddleware:
    - name: webpackDevMiddleware
      beforeMiddleware: serveResources
      mountPath: /webpack
      configuration:
        path: "./webapp/modules/viewer/adapter/webpack.config.js"
---
specVersion: "1.0"
kind: extension
type: server-middleware
metadata:
  name: webpackDevMiddleware
middleware:
  path: cli/middlewares/webpack-dev-middleware.js
```
3. Run `ui5 serve`

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.13.1`
- Node.js Version: `v12.16.0`
- npm Version: `6.13.4`
- OS/Platform: `Windows 10 1809 (OS Build 17763.973)`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [X] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
WARN types:library:LibraryFormatter Failed to detect namespace or namespace is empty for project themelib_sap_fiori_3. Check verbose log for details.

⚠️  Process Failed With Error

Error Message:
middlewareRepository: Unknown Middleware webpackDevMiddleware

For details, execute the same command again with an additional '--verbose' parameter
```
With `--verbose` flag:
```
[...]
⚠️  Process Failed With Error

Error Message:
middlewareRepository: Unknown Middleware webpackDevMiddleware

Stack Trace:
Error: middlewareRepository: Unknown Middleware webpackDevMiddleware
    at Object.getMiddleware (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\middlewareRepository.js:18:9)
    at MiddlewareManager.addMiddleware (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:37:49)
    at MiddlewareManager.addCustomMiddleware (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:176:15)
    at MiddlewareManager.applyMiddleware (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:25:14)
    at async Object.serve (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\node_modules\@ui5\server\lib\server.js:137:3)
    at async Object.serve.handler (D:\DanielL\Documents\Repositories\ortec-load-building-visualization\repository\node_modules\@ui5\cli\lib\cli\commands\serve.js:108:33)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-server/issues/new
```
