### ISSUE TITLE
Option to only build certain dependencies

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-tooling#348]
## Expected Behavior
There sould be an posibility to build only certen Dependencies and not onyl all

## Current Behavior
it is only possible to ignore some dependencies in dev mode

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.2.1`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

The originated problem is that we have a shim for @babel/polyfill

```
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
    name: babel-polyfills
shims:
    configurations:
        "@babel/polyfill": # name as defined in package.json
            specVersion: "1.0"
            type: module # Use module type
            metadata:
                name: "babel-polyfills"
            resources:
                configuration:
                    paths:
                        /lib/babel/: "dist"
```
when building we want to build this shim but not all other dependencies. that way we could just zip the dist folder and upload that to the SAP Gateway
