### ISSUE TITLE
Define sources to be included/excluded from library-preload.js

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#368]
## Expected Behavior
For my library-preload.js I want to exclude individual resources from the preload bundle.

## Current Behavior
For the Component-preload.js this exclusion works by declaring the bundle definition in the `ui5.yaml`:

```
builder:
  bundles:
  - bundleDefinition:
      name: component_folder/Component-preload.js
      defaultFileTypes:
      - ".js"
      - ".fragment.xml"
      - ".view.xml"
      - ".properties"
      - ".json"
      sections:
      - mode: preload
        filters:
        - your_filters_here
        resolve: false
    bundleOptions:
      optimize: true
      usePredefineCalls: true
```

For libraries I would expect to do the same and to repeat the bundle definition in the `ui5.yaml`, e.g.:

```
builder:
  bundle:
  - bundleDefinition:
      name: sap/ui/table/library-preload.js
      defaultFileTypes:
      - ".js"
      - ".fragment.xml"
      - ".view.xml"
      - ".properties"
      - ".json"
      sections:
      - mode: preload
        filters:
        - "sap/ui/table/"
        - "!sap/ui/table/.library"
        - "!sap/ui/table/themes/"
        - "!sap/ui/table/messagebundle*"
        resolve: false
        resolveConditional: false
        renderer: true
```

## Steps to reproduce the issue
1. Add the bundle definition above to the `ui5.yaml` of sap.ui.table
2. Run `ui5 build`

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.5.2`
- Node.js Version: `not relevant`
- npm Version: `not relevant`
- OS/Platform: `not relevant`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)
