### ISSUE TITLE
Dependency test-resources should be omitted in build

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#379]
## Expected Behavior
`test-resources` of project dependencies shall not be part of a (production) build 

## Current Behavior
`test-resources` folder is part of the build result

## Steps to reproduce the issue
1. Clone ui5lab sample library
` git clone https://github.com/UI5Lab/UI5Lab-library-simple`

2. Build library
` ui5 build --a`

3. Check the content of the `dist` folder - contains `test-resources` of dependencies
```shell
UI5Lab-app-simple (master)
$ ls -1 ./dist
Component.js
Component-dbg.js
Component-preload.js
controller/
css/
i18n/
index.html
indexSelfContained.html
manifest.json
model/
resources/
test/
test-resources/ <---- test resources of ui5lab-library dependency
view/
```

**Comment by henriquemattos** [comment]
Hi, @RandomByte . Any news on this topic? Or is it safe to exclude tests with any CLI param?

Cheers, Henrique

**Comment by RandomByte** [comment]
This issue is rather old and didn't get updated. By now you can configure excludes for resources like `/test-resources/**` in the ui5.yaml: https://sap.github.io/ui5-tooling/stable/pages/Configuration/#exclude-resources

@matz3 should we close this? I think the main requirement got implemented. Although we could discuss the default behavior more.

**Comment by CLVNSwan** [comment]
In current version the "test-resources" folder is still part of the dist folder, including all dependencies 

UI5 CLI Version: 
```text
3.11.0
```

UI5 YAML Version:
```text
3.2
```

console script: 
```text
ui5 build --clean-dest --all 
```

ui5.yaml
```yaml
specVersion: "3.2"
metadata:
    name: **hide**
type: application
framework:
    name: OpenUI5
    version: 1.120.10
    libraries:
        - name: sap.f
        - name: sap.m
        - name: sap.ui.core
        - name: sap.ui.layout
        - name: themelib_sap_horizon
        - name: sap.tnt
resources:
    configuration:
        paths:
            webapp: /out
builder:
    resources:
        excludes:
            - "/localService/**"
            - "/test/**"
            - "/test-resources/**"
```

current output: 
```yaml
- dist 
  - resources
  - test-resources
  - ...additionalFiles
```

expected output: 
```yaml
- dist 
  - resources
  - ...additionalFiles
```
