### ISSUE TITLE
Legacy Bundling Tool includes "some" JSDoc comments

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#445]
## Current Behavior
When running a build for a custom bundle defined in a `ui5.yaml` I expect that the JSDoc comments will be removed. When running a custom bundle build including `sap/ui/core/ManageObject` the constructor comment will not be removed from the bundle, e.g.:

```yml
specVersion: '1.0'
metadata:
  name: sample
type: application
builder:
  bundles:
  - bundleDefinition:
      name: bundle.js
      defaultFileTypes:
      - ".js"
      sections:
      - mode: preload
        filters:
        - sap/ui/base/ManagedObject.js
        resolve: false
        sort: true
        declareModules: false
    bundleOptions:
      optimize: true
      usePredefineCalls: false
```

After running ui5 build with this configuration you can see that the bundle.js includes this huge JSDoc comment. 

But when changing this bundle definition to use predefine calls then the JSDoc is being remove properly.

## Expected Behavior
The JSDoc comments should be removed from the bundle.

## Steps to reproduce the issue
1. Put the content of the ui5.yaml above in your UI5 tooling based project as ui5-test.yaml
2. Run ui5 build --config ui5-test.yaml
3. Check the output in dist/resources/bundle.js => includes constructor comment
4. Run the build again with usePredefineCalls: true => no comments

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.4.4`
- Node.js Version: `8.9.1`
- npm Version: `5.7.1`
- OS/Platform: `macos`
- Browser *(if relevant)*: `not relevant`
- Other information: `n/a`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)
