### ISSUE TITLE
Also serve application projects in /resources

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#45]
## Expected Behavior
In some use cases, it is desired to use multiple ui5 components in a shared environment (for instance loading an application component _appB_ file during runtime once a tile was clicked in _appA_). This is currently possible with HTML5 / ui5 applications that are deployed in a SCP account, in conjunction with a configuration in `neon-app.json`. 

## Current Behavior
As of now, ui5 application projects won’t be served in `/resources `when running `ui5 serve` in a ui5 root project, even when they contain an `ui5.yaml` descriptor file and are listed as dependencies.

## Steps to reproduce the issue
Suppose the following structure of two ui5 application projects:

```
my-root-app/
    \_ node_modules/
    \_ webapp/
    \_ ui5.yaml
    \_ package.json

openui5-sample-app
    \_ node_modules/
    \_ webapp/
    \_ ui5.yaml
    \_ package.json
```

A global link of the `openui5-sample` app is created:
```
cd openui5-sample-app
npm link 
```

The sample app is added as a dependency
```
cd my-root-app
npm link openui5-sample-app
npm install 
```

The ui5-sample-app is made known in the root project:
```html
	<script id="sap-ui-bootstrap" type="text/javascript"
		src="resources/sap-ui-core.js"
		data-sap-ui-theme="sap_belize"
		data-sap-ui-libs="sap.m"
		data-sap-ui-bindingSyntax="complex"
		data-sap-ui-compatVersion="edge"
		data-sap-ui-preload="async"
		data-sap-ui-resourceroots='{
			"my.app: './',
			"sap.ui.demo.todo": "/resources/sap/ui/demo/todo"
		}'>
	</script>
```

However, when running `ui5 serve` in _my-root-app_, requests that point to the _openui5-sample-app_ will fail.

**Comment by RandomByte** [comment]
Instead of enhancing the application type, @matz3 and I discussed the possibility of adding "component" types which are always served at their namespace (e.g. `/resources/my/todo/app`).

Application projects would then only act as an entry point or test environment (e.g. the OpenUI5 [testsuite](https://github.com/SAP/openui5/tree/master/src/testsuite), which is actually not a *__UI5__* application) and will continue to be served at `/` and enforced to be at the root of a dependency tree that contains an application project.

This setup would be closer to how many apps are being developed, especially in the Fiori Launchpad context.

CC @codeworrior @petermuessig

**Comment by sebbi08** [comment]
hi Currently we are doing a workaround with defining the Project as shim

```
---
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
    name: openui5-sample-app
shims:
    configurations:
        "openui5-sample-app": # name as defined in package.json
            specVersion: "1.0"
            type: module # Use module type
            metadata:
                name: "openui5-sample-app"
            resources:
                configuration:
                    paths:
                        /resources/open/ui5/sample/: "webapp"
```

this comes with the problem that the shims in the sub project are not applyed corrertly

they are applyed but on root level an not the level of the subproject
