### ISSUE TITLE
Invalid Resource: Must be instance of @ui5/fs.Resource

### ISSUE THREAD

**Issue by ssimsekler** [SAP/ui5-tooling#458]
Hello

Our CI pipeline stopped working after the recent release of the version 2.4.0. It raised the following error:

```
...
verb resources:adapters:FileSystem Writing to dist/controller/MessagesPopover-dbg.js
verb resources:adapters:FileSystem Writing to dist/controller/EmailMaintDialog.js
ERR! builder:builder Build failed in 1.12 s
info builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
Invalid Resource: Must be instance of @ui5/fs.Resource

Stack Trace:
Error: Invalid Resource: Must be instance of @ui5/fs.Resource
    at ResourceTagCollection._validateResource (/__w/1/s/bp/node_modules/@ui5/cli/node_modules/@ui5/fs/lib/ResourceTagCollection.js:51:10)
    at ResourceTagCollection.getTag (/__w/1/s/bp/node_modules/@ui5/cli/node_modules/@ui5/fs/lib/ResourceTagCollection.js:40:8)
    at Promise.all.resources.map (/__w/1/s/bp/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/builder/builder.js:360:26)
    at Array.map (<anonymous>)
    at workspace.byGlob.then (/__w/1/s/bp/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/builder/builder.js:359:36)
...
```

**The problem was resolved when we changed our @ui5/cli version dependency to "~2.3.2".**

Relevant part of package.json:

```
   "scripts": {
        "build": "npm run clean && ui5 build --verbose --include-task=generateManifestBundle generateCachebusterInfo && npm run zip",
        "zip": "cd dist && npx bestzip ../bp-content.zip *",
        "clean": "npx rimraf bp-content.zip dist"
    },
    "ui5": {
        "dependencies": [
            "@sap/ui5-builder-webide-extension"
        ]
    }
```

ui5.yaml:

```
specVersion: '1.0'
metadata:
  name: bp
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  customTasks:
  - name: webide-extension-task-updateManifestJson
    afterTask: generateVersionInfo
    configuration:
      appFolder: webapp
      destDir: dist
  - name: webide-extension-task-resources
    afterTask: webide-extension-task-updateManifestJson
    configuration:
      nameSpace: centrica/sapcloud/microgen/ui
  - name: webide-extension-task-copyFile
    afterTask: webide-extension-task-resources
    configuration:
      srcFile: "/xs-app.json"
      destFile: "/xs-app.json"
```

## Expected Behavior
Build to succeed

## Current Behavior
Build fails with the error log mentioned above.

## Steps to reproduce the issue
1. Run CDS_ENV=production mbt build

## Context
- Container used in pipeline: `ppiper/mta-archive-builder:latest`
- OS/Platform: `ubuntu`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [X] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```
