### ISSUE TITLE
Allow to share configuration between middlewares

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/ui5-tooling#462]
Hi!

Currently writing multiple middleware ( cannot be wrapped into one as used in different moments ) I found out that it's not possible to share configuration between them.

Yes, we have resources - but then we need to detect which is active config and then read and parse yaml manually.

So one of solutions is to use a separate file or environment variables, but more elegant solution to my opinion might be give an option to read the whole configuration file from middleware util.

One of the use cases is to write extensions for existing middlewares ( like fiori-tools-proxy ) when we don't copy configuration but just reading it from the global config.

As a simple workaround - it might be easier to provide also custom customConfiguration as a parameter or util method.

Thank you!

**Comment by ThePlenkov** [comment]
I have solved my task currently by using yaml merge:
```yaml
specVersion: "2.2"
#type: application|library|theme-library|module
type: library
metadata:
  name: test
customConfiguration: &global
  fiori-tools-proxy: &fiori-tools-proxy
    ui5:
      path:
        - /resources
        - /test-resources
      url: https://sapui5.hana.ondemand.com
      version: 1.78.0
  myTool:
    key: value
  myOtherTool:
    otherKey: otherValue
server:
  customMiddleware:    
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration: 
        <<: *fiori-tools-proxy        
    - name: fiori-tools-home-page
      beforeMiddleware: serveIndex
      configuration: 
        <<: *global        
    - name: fiori-tools-proxy-cdn
      beforeMiddleware: fiori-tools-proxy
      configuration: 
        <<: *global
```

It works but then it requires ui5.yaml configuration which impacts middleware's usability
