### ISSUE TITLE
`ui5 use` may corrupt ui5.yaml

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-tooling#474]
## Expected Behavior
`ui5 use latest` should add the latest version to the ui5.yaml, keeping the other configuration intact.

## Current Behavior
Executing `ui5 use latest` in a project with the following ui5.yaml content (missing `version`):
```yaml
specVersion: '2.0'
metadata:
  name: openui5-sample-app
type: application
framework:
  name: OpenUI5
  libraries:
    - name: sap.ui.core
builder:
  resources:
    excludes:
      - "something"
```

will result in
```yaml
specVersion: '2.0'
metadata:
  name: openui5-sample-app
type: application
framework:
  name: OpenUI5
  libraries:
    - name: sap.ui.core
b  version: "1.85.2"
uilder:
  resources:
    excludes:
      - "something"
```

Note how the `b` from `builder` has moved in front of the "version" property

## Steps to Reproduce the Issue

1. `git clone --branch bug-demo-ui5-use git@github.com:SAP/openui5-sample-app.git`
2. `cd openui5-sample-app`
3. `npm install`
4. `ui5 use latest`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.7.0`**
 * Node.js Version: **`v14.15.1`**
 * npm Version: `6.14.9`
 * OS/Platform: `macOS 10.15.7`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
❯ ui5 use latest
Updated configuration written to ui5.yaml
This project is now using SAPUI5 version 1.85.1
```
