### ISSUE TITLE
Failed to find SAPUI5 framework library

### ISSUE THREAD

**Issue by htammen** [SAP/ui5-tooling#487]
## Expected Behavior
I expect the sap.m library added to my UI5 application

## Current Behavior
`ui5 add sap.m` throws this error (last lines of the error message)
```
http fetch GET 304 https://registry.npmjs.org/@sapui5%2fdistribution-metadata 293ms (from cache)
http fetch GET 200 https://registry.npmjs.org/@sapui5/distribution-metadata/-/distribution-metadata-1.85.2.tgz 15ms (from cache)
verb normalizer:ui5Framework:npm:Installer Promoting staging directory from C:\Users\tammen\.ui5\framework\staging\@sapui5-distribution-metadata-1.85.2 to C:\Users\tammen\.ui5\framework\packages\@sapui5\distribution-metadata\1.85.2...
verb normalizer:ui5Framework:npm:Installer Unlocking C:\Users\tammen\.ui5\framework\locks\package-@sapui5-distribution-metadata@1.85.2.lock

⚠️  Process Failed With Error

Error Message:
Failed to find SAPUI5 framework library sap.m: EPERM: operation not permitted, rename 'C:\Users\tammen\.ui5\framework\staging\@sapui5-distribution-metadata-1.85.2' -> 'C:\Users\tammen\.ui5\framework\packages\@sapui5\distribution-metadata\1.85.2'

Stack Trace:
Error: Failed to find SAPUI5 framework library sap.m: EPERM: operation not permitted, rename 'C:\Users\tammen\.ui5\framework\staging\@sapui5-distribution-metadata-1.85.2' -> 'C:\Users\tammen\.ui5\framework\packages\@sapui5\distribution-metadata\1.85.2'
    at D:\programs\node\node-v14.15.4-win-x64\node_modules\@ui5\cli\lib\framework\add.js:38:10
    at async Promise.all (index 0)
    at async module.exports (D:\programs\node\node-v14.15.4-win-x64\node_modules\@ui5\cli\lib\framework\add.js:34:2)
    at async Object.addCommand.handler (D:\programs\node\node-v14.15.4-win-x64\node_modules\@ui5\cli\lib\cli\commands\add.js:59:24)
```
This error is thrown for all libraries I added to the `ui5.yaml` when I run `ui5 serve`

## Steps to Reproduce the Issue
Don't really know how to reproduce it. Is it my node.js version (14.15.4) or the UI5 version 1.85.2, my @ui5/cli version or the fact that I'm behind a proxy?

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.9.0 (from D:\programs\node\node-v14.15.4-win-x64\node_modules\@ui5\cli\bin\ui5.js)`**
 * Node.js Version: **`v14.15.4`**
 * npm Version: `6.14.10`
 * OS/Platform: `Windows 10.0.18363`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `I'm working behind a proxy, but npm install can install all packages from the internet`

## Log Output / Stack Trace
See above

**Comment by htammen** [comment]
Here is my `ui5.yaml`

```
specVersion: '2.2'
metadata:
  name: UserApp
type: application
framework: 
  name: SAPUI5
  version: "1.85.2"
  libraries:
    - name: sap.f
    - name: sap.tnt
    - name: sap.ui.core
    - name: sap.ui.layout
    - name: sap.uxap
    - name: themelib_sap_belize
    - name: themelib_sap_fiori_
```
