### ISSUE TITLE
Option to only build certain dependencies

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-tooling#494]
## Expected Behavior
There sould be an posibility to build only certen Dependencies and not onyl all

## Current Behavior
it is only possible to ignore some dependencies in dev mode

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.2.1`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

The originated problem is that we have a shim for @babel/polyfill

```
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
    name: babel-polyfills
shims:
    configurations:
        "@babel/polyfill": # name as defined in package.json
            specVersion: "1.0"
            type: module # Use module type
            metadata:
                name: "babel-polyfills"
            resources:
                configuration:
                    paths:
                        /lib/babel/: "dist"
```
when building we want to build this shim but not all other dependencies. that way we could just zip the dist folder and upload that to the SAP Gateway

**Comment by RandomByte** [comment]
@larskissel is currently working on implementing this feature. For anyone interested, please checkout the details in https://github.com/SAP/ui5-cli/pull/442 and especially the descriptions of the new CLI parameters [here](https://github.com/SAP/ui5-cli/pull/442/files#diff-fa417d561a90d4778c29fa54777d73599d9eec3c0b61e09fc586c282d951a964R41-R72) 🙌

**Comment by RandomByte** [comment]
Released as part of UI5 CLI [v2.12.0](https://github.com/SAP/ui5-cli/releases/tag/v2.12.0) 🎉 

Check the documentation [here](https://sap.github.io/ui5-tooling/pages/Configuration/#include-dependencies) (ui5.yaml) and [here](https://sap.github.io/ui5-tooling/pages/Configuration/#include-dependencies) (CLI).

**Comment by sebbi08** [comment]
@RandomByte i tried this out but when doing it the the ui5.yaml config like

```
builder:
    settings:
        includeDependency:
            - babel-polyfills
```

it is giving me the error : 
```
⚠️  Process Failed With Error

Error Message:
Invalid ui5.yaml configuration for project bsh-ess-edd

Configuration builder property settings must not be provided here

```
