### ISSUE TITLE
Allow `server` configuration with type `module`

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/ui5-tooling#536]
## Is your feature request related to a problem? Please describe.

I want to use the ui5 cli to serve multiple UI5 apps at once, ideally in a fiori launchpad, with live reload. With `type: module`, I can mount my apps like this:

```yaml
resources:
  configuration:
    paths:
      /app1/: app1/webapp
      /app2/: app2/webapp
```

I try to configure the community live reload extension like this:

```yaml
server:
  customMiddleware:
  - name: ui5-middleware-livereload
    afterMiddleware: compression
    configuration:
      debug: true
      extraExts: "xml,json,properties"
      port: 35729
      watchPath:
        - app1/webapp
        - app2/webapp
```

However, this fails the schema validation. However, I _can_ start a server if I don't try to configure it, which makes me feel that either `ui5 serve` should fail for `module`s, or I should be able to configure it.

I went ahead and just added the definition in the schema definition in node modules. With this, validation passed and the server came up with the middleware running (and working fine)

## Describe the solution you'd like

Please add the `server` options for `type: module`.

## Describe alternatives you've considered

I've tried to switch to type `application`, but then I wasn't allowed the path configuration I needed.

Maybe this is beyond the current scope and requires a new module type in the long run, but as a shorter-term solution allowing the middleware would already be great.

Thank you for considering this requeset!
Kind regards
Lukas
