### ISSUE TITLE
mountPath for middleware is not supporting array or regex

### ISSUE THREAD

**Issue by piejanssens** [SAP/ui5-tooling#576]
## Expected Behavior
Support arrays for mountPath just like express does

## Current Behavior
It's not supported

## Steps to Reproduce the Issue

1. add middleware with array definition for mountPath

```
    - name: ui5-middleware-simpleproxy
      afterMiddleware: ui5-middleware-stringreplacer
      mountPath:
        - '/ci/'
        - '/v2/'
        - '/sf/'
 ```

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): 2.13
 * Node.js Version: **`14`**
 * npm Version: `8.1`

## Log Output / Stack Trace

```
Configuration server/customMiddleware/1/mountPath must be of type 'string'

/home/pieter/projects/xxx/app/ui5.yaml:17

15:     - name: ui5-middleware-simpleproxy
16:       afterMiddleware: compression
17:       mountPath:
```
