### ISSUE TITLE
Builder is adding libraries that are not in ui5.yaml

### ISSUE THREAD

**Issue by piejanssens** [SAP/ui5-tooling#590]
ui5 version 2.14.1

```
framework:
  name: SAPUI5
  version: "1.96.0"
  libraries:
    - name: sap.m
    - name: sap.suite.ui.commons
    - name: sap.ui.core
    - name: sap.ui.layout
    - name: sap.ui.unified
    - name: themelib_sap_fiori_3
```

Build command: `ui5 build -a --clean-dest`

I am not using these libararies, yet they are being built:

- sap.viz
- sap.chart
- sap.suite.ui.microchart
- sap.ui.comp
- sap.ui.ux3
- sap.ui.fl
- ...

**Comment by RandomByte** [comment]
Apparently, these are transitive dependencies of `sap.suite.ui.commons`.

From the [library's](https://npmjs.com/package/@sapui5/sap.suite.ui.commons) ui5.yaml:

```yaml
specVersion: '1.0'
type: library
metadata:
  name: sap.suite.ui.commons
framework:
  name: SAPUI5
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.suite.ui.microchart
    - name: sap.ui.ux3
    - name: sap.ui.comp
    - name: sap.viz
    - name: sap.ui.commons
    - name: themelib_sap_horizon
      optional: true
    - name: themelib_sap_fiori_3
      optional: true
    - name: themelib_sap_belize
      optional: true
    - name: themelib_sap_bluecrystal
      optional: true
```

Nothing UI5 Tooling can do here 🤷
