### ISSUE TITLE
[Feature Request]: Allow merging of multiple config files

### ISSUE THREAD

**Issue by jakubledl** [SAP/ui5-tooling#704]
## Is your feature request related to a problem? Please describe.

In many projects, including now our own, one sees two or three different YAML configurations for UI5, each doing a different thing (one running with the mockserver middleware, a different one with the fiori local middleware &c.), but all sharing a lot of common information.

## Describe the solution you'd like

Suppose I have e.g. `ui5.yaml`:

```yaml
specVersion: "2.0"
metadata:
  name: ...
type: application
...
```

and `mockserver.yaml`:

```yaml
server:
  customMiddleware:
    - name: sap-fe-mockserver
      beforeMiddleware: compression
      configuration:
        service:
          ...
```

I would like to be able to run e.g. `ui5 serve --config ui5.yaml --config mockserver.yaml` and have the two config files effectively merged into one configuration.

## Describe alternatives you've considered

- `cat`ting the config files together and passing it to `ui5`, but besides being wonky, the UI5 CLI doesn't support passing configuration on stdin
- pasting the two configs into a new file using a pre-run NPM script, passing that to `ui5 serve`, deleting it afterwards (also not great)
