### ISSUE TITLE
CF deploy fails with manifest.json not found

### ISSUE THREAD

**Issue by wozjac** [SAP/ui5-tooling#772]
## Expected Behavior
Deploy to CF is successful

## Current Behavior
Deploy to CF fails with the tooling 3.0.0 with
```sh
[ERROR] Upload application content failed { CODE: '1001' } validation error: manifest.json not found
```
using `fiori cfDeploy` to deploy.

- the project was using tooling ver 2.14.17
- build script was: `ui5 build preload --clean-dest --include-task=generateManifestBundle  .... `
- build script now adapted to 3.0.0 is: `ui5 build preload --clean-dest .... ` - just this task removed according to [07a5be2](https://github.com/SAP/ui5-builder/commit/07a5be2b6d9aa23cf78ddd17951c832d6dec7bef)
- no other changes introduced in the project

Project type is `library`. Do we miss other required adaptation for tooling 3.0.0?

**Comment by nzamani** [comment]
Is it really not needed anymore by SAPCF anymore? 

![28992B49-FC0F-4C71-8B63-7F51D8FF2E1F](https://user-images.githubusercontent.com/884161/218053324-2de40aa7-1554-4d76-b21e-dbf7b393b3d0.jpeg)

**Comment by matz3** [comment]
@wozjac thanks for reporting this. Unfortunately we can't fully reproduce or understand what's going wrong in your scenario.
Could you please provide the project sources or a sample project where this can be reproduced?

**Comment by wozjac** [comment]
Hi,

so we have a library project.
The structure is - in a nutshell - like this:

```sh
src
  our
    lib
      .library
      library.js
      manifest.json
      somefile.js
      ....
test
...
package.json
...
```

We deploy it as MTA, after building with `mbt build`.
In `mta.yaml`:

```yaml
...
- name: our-lib
    type: html5
    path: .
    build-parameters:
      build-result: dist
      builder: custom
      commands:
        - npm install
        - npm run build:cf
```

Build script `"build:cf"` (adjusted for 3.0.0) is: `ui5 build preload --clean-dest`
Deploy "fiori cfDeploy".

As I wrote with the tooling version 2 it was working (with `--include-task=generateManifestBundle` in `build:cf` script).

BR,
Jacek

**Comment by MatthiasSchmalz** [comment]
Hi Jacek,

could you please show us how the content of the assembled MTAR looks like?  
It should contain the library build result in a nested zip file. What is the file structure inside?

Also could you do the same build with the old tooling and show the same as a comparison?

Best regards  
Matthias

**Comment by RandomByte** [comment]
If possible, kindly also share the log output of `ui5 build --verbose` with us. Ideally for both versions, but at least for version 3.

**Comment by longieirl** [comment]
@wozjac  does your project have a ui5-deploy.yaml script? Can you please append it;

Here is a sample;
```YAML
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json
specVersion: '2.4'
metadata:
  name: mtalibrary
type: library
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  resources:
    excludes:
      - "/test/**"
      - "/localService/**"
  customTasks:
  - name: ui5-task-zipper
    afterTask: minify
    configuration:
      archiveName: mtalibrary
      additionalFiles:
      - xs-app.json
```
Replace `mtalibrary` with appropiate names of your project. 

The `package.json` command `build:cf` now looks like this;
```
 "build:cf": "ui5 build preload --clean-dest --config ui5-deploy.yaml"
```
If you review the generated zip file from this command which will in turn be used during the CF deployment flow, it should contain the manifest.json.
John

**Comment by wozjac** [comment]
Thanks for all responses, a quick question - is this still required? It is currently in our legacy projects:

```yaml
  customTasks:
    - name: ui5-task-flatten-library
      afterTask: generateResourcesJson
```

**Comment by matz3** [comment]
@longieirl how did the file look before upgrading to v3? `afterTask: minify` refers to the new minify task which is now executed at a different point in time in the build process compared to the removed `uglify` task, see https://sap.github.io/ui5-tooling/stable/updates/migrate-v3/.
Maybe this causes issues when deploying the project?

**Comment by longieirl** [comment]
@wozjac without knowing your project structure/code, my understanding is `ui5-task-flatten-library` is typically used in an ABAP deployment scearnio. If you can provide more configuration files to review, that would be great.

**Comment by wozjac** [comment]
Thanks for all suggestions, I will try tomorrow apply & check them.

**Comment by wozjac** [comment]
Here are some details for experiments.

1. Build results from the current project setup.
- UI5 tooling: 2.14.17
- ui5-task-flatten-library: 0.2.5,
- ui5-task-zipper: 0.6.1
- build script: `ui5 build preload --clean-dest --include-task=generateManifestBundle`
- `ui5.yaml`:
```yaml
specVersion: "2.6"
metadata:
  name: my-lib
type: library

framework:
  name: SAPUI5
  version: 1.108.4
  libraries:
    - name: sap.ui.core
    - name: themelib_sap_horizon

builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:
    - name: ui5-task-flatten-library
      afterTask: generateResourcesJson

    - name: ui5-tooling-transpile-task
      afterTask: escapeNonAsciiCharacters
      configuration:
        debug: false
        removeConsoleStatements: true
        transpileAsync: true

    - name: ui5-task-zipper
      afterTask: ui5-task-flatten-library
      configuration:
        archiveName: my-lib
        additionalFiles:
          - xs-app.json
```
- the result in the `dist` folder:
![image](https://user-images.githubusercontent.com/20969653/218691993-c4dba078-c0cb-4369-b93d-986e244195ab.png)

- `my-lib.zip` content:
![image](https://user-images.githubusercontent.com/20969653/218692246-d107445c-b5fc-4bc1-9b41-6c886393b0e0.png)

2. Upgrading things:
- UI5 Tooling: 3.0.0
- ui5-task-flatten-library: 0.3.0
- ui5-task-zipper: 0.7.3

a. first approach, adjusted the build script to: `ui5 build preload --clean-dest`
- flatten + zipper ran at the end
![image](https://user-images.githubusercontent.com/20969653/218711166-a8f83448-f259-41b2-973e-e9450733172b.png)

- the result in the `dist` folder - looks ok
![image](https://user-images.githubusercontent.com/20969653/218695305-68f25273-c788-4f48-9f62-e0dffab3d0fb.png)

- `my-lib.zip` content - **only xs-app.json**, no other files present
![image](https://user-images.githubusercontent.com/20969653/218695535-fd9f9e63-643e-496a-a978-c3a2d48aa241.png)

Side note: on https://www.npmjs.com/package/ui5-task-zipper page there is stated that:
![image](https://user-images.githubusercontent.com/20969653/218696082-d657847c-a3b8-433e-9b81-22c0d9be12de.png)

- this task is no longer run by default and only present for `application` project types so IMHO it is worth mentioning this on the zipper page:
![image](https://user-images.githubusercontent.com/20969653/218696527-0643e7f8-f5cd-4ee9-8c65-d911c4f4b7c8.png)

b. I removed the task for flattening, zipper set after `buildThemes`
```yaml
specVersion: "2.6"
metadata:
  name: my-lib
type: library

framework:
  name: SAPUI5
  version: 1.108.4
  libraries:
    - name: sap.ui.core
    - name: themelib_sap_horizon

builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:

    - name: ui5-tooling-transpile-task
      afterTask: escapeNonAsciiCharacters
      configuration:
        debug: false
        removeConsoleStatements: true
        transpileAsync: true

    - name: ui5-task-zipper
      afterTask: buildThemes
      configuration:
        archiveName: my-lib
        additionalFiles:
          - xs-app.json
``` 

- build result:
![image](https://user-images.githubusercontent.com/20969653/218699448-23a0a6b6-346d-4fda-a7aa-717176bbabd4.png)
- `resources` is OK, contains project files (keeping the folder structure etc.)
- `my-lib.zip` content - looks the same as in the legacy setup from point 1 with flattening, deployment to CF is OK:
![image](https://user-images.githubusercontent.com/20969653/218699940-c757bdf9-dd9b-4019-821b-e3f0eaeb5e77.png)
- for the ABAP deployment the structure in the `dist` is not flat (the project in the transition phase needs to target both ABAP and CF). 
- so the project has always been running flattening, but in fact this can be limited with inlcude/exclude task just for ABAP deployment. Seems that with the old tooling the zipper task was just taking the `dist` content in both scenarios (flat/normal).
