### ISSUE TITLE
Failed to load reuse component with 3.0

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-tooling#785]
## Expected Behavior
Start a app and load a library with `componentUsages` and `resourceRoots`

## Current Behavior
App does not find component
<img width="648" alt="image" src="https://user-images.githubusercontent.com/13335743/219493620-cb1b0451-2ce5-4b13-8456-0e345a299dc1.png">
When changing to cli 2.14.17 it works. With 3.0.1 it does not.  
Any breaking changes here? Only difference is the version change.  
see here for the apps ´[manifest.json](https://github.com/marianfoo/ui5-cc-excelUpload/blob/chore/update-dependencies/examples/packages/ordersv4fe/webapp/manifest.json)´

Please check if you can reproduce the error or i might have missed something in the steps

## Steps to Reproduce the Issue
1. `git clone https://github.com/marianfoo/ui5-cc-excelUpload`
2. `git checkout chore/update-dependencies`
3. `pnpm i`
4. `npm run build`
5. `npm run start:server`
6. `npm run start:v4fe:108`
8. Press "Excel Upload" Button (List Report, right upper corner)  --> nothing happens, 404 Error not found in console
9. Stop UI5 App
10. Change to UI5 CLI 2.14.17 here --> https://github.com/marianfoo/ui5-cc-excelUpload/blob/6125af1bcb96e9b29ad76434e267b6fa01a588da/examples/packages/ordersv4fe/package.json#L19
11. `pnpm i`
12. `npm run start:v4fe:108`
14. Press "Excel Upload" Button --> Dialog appears
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/13335743/219495122-d8f2bd8d-6866-4ff6-b5a3-4cd877ab7171.png">

## Context
 * Node.js Version: **`18.14.0`**
 * npm Version: `unknown`
 * OS/Platform: `mac`
 * Browser *(if relevant)*: `chrome`
 * Other information regarding your environment *(optional)*: `nothing`

**Comment by RandomByte** [comment]
Thanks for reporting! This is indeed caused by an involuntarily breaking change.

Essentially, shims contained in the same module as a project won't be applied to that project anymore.

In your project, you have the following ui5.yaml configuration for module `ui5-cc-excelupload`:

```yaml
specVersion: "2.6"
type: module
metadata:
  name: ui5-cc-excelupload
---
specVersion: "2.6"
kind: extension
type: project-shim
metadata:
  name: thirdparty
shims:
  configurations:
    ui5-cc-excelupload:
      specVersion: "2.6"
      type: module
      metadata:
        name: ui5-cc-excelupload
      resources:
        configuration:
          paths:
            "/thirdparty/customControl/excelUpload/v0/8/1/": "./dist/"
```

This is a **project `ui5-cc-excelupload`** and an **extension `thirdparty`**, containing a configuration for the project.

With UI5 Tooling v2, the shim used to [be applied to the already created project](https://github.com/SAP/ui5-project/blob/98094c421539e8edc032e903b96c6f8d80b59bfb/lib/projectPreprocessor.js#L87).

In UI5 Tooling v3, there are two relevant changes:
1. Shims can only be applied during the _creation_ of a project
2. The project and extensions of a module are created at the same time

So the behavior you are observing is by design. You can resolve this by moving the configuration from the shim to the module itself, like this:

```yaml
specVersion: "2.6"
type: module
metadata:
  name: ui5-cc-excelupload
resources:
  configuration:
    paths:
      "/thirdparty/customControl/excelUpload/v0/8/1/": "./dist/"
```

To better understand your scenario, could you share some details on why you chose to configure the project via the shim extension?
