### ISSUE TITLE
UI5 Tooling 3.0: `ui5 init` creates a `ui5.yaml` with `specVersion: 2.6` instead of `specVersion: 3.0`

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#815]
## Expected Behavior
When initializing an empty NPM project having a webapp folder with `ui5 init` the created `ui5.yaml` should look like that:

```yaml
specVersion: '3.0'
metadata:
  name: myapp
type: application
```

## Current Behavior
Today `ui5 init` creates a `ui5.yaml` with:

```yaml
specVersion: '2.6'
metadata:
  name: myapp
type: application
```

## Steps to Reproduce the Issue
See above

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`3.0.6`**
rest is not relevant
