### ISSUE TITLE
UI5 Tooling: Specifying libraries dependencies in ui5.yaml

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#949]
Playing with UI5 Tooling, I see that the **ui5.yaml** config file contains a framework library section, where we supposed to specify UI5 app dependencies, e.g. `sap.m`, `sap.ui.core` etc.:

```yaml
specVersion: "3.2"
type: application
metadata:
    name: com.myApp
framework:
    name: OpenUI5
    version: 1.124.0
    libraries:
        -   name: sap.m
        -   name: sap.ui.core
```

My questions:

 1. Should the `framework/libraries` section of **ui5.yaml** be identical to the `sap.ui5/dependencies/libs` one of **manifest.json**?

 2. If I understand it correctly, these `framework/libraries` section is used to incorporate these libs into `Component-preload.js`. Is it a correct assumption?

 3. Should I specify this `libraries` section at all in case, if I consume UI5 lib from the CDN?
